services:
  url-shortener:
    image: "url-shortener"
    build: .
    container_name: "url-shortener"
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ".env"
  mysql:
    image: "mysql:8.0.0"
    container_name: "mysql"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_USER: "ahsp"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "url_shortener"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
