version: "3"
services:
  url-shortener:
    image: "url-shortener"
    build: .
    container_name: "url-shortener"
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - ".env"
    depends_on:
      mysql:
        condition: "service_healthy"
        restart: true
  mysql:
    image: "mysql:8.0.0"
    container_name: "mysql"
    environment:
      MYSQL_USER: "ahsp"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "url_shortener"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
